import { conflict, forbidden, missing } from './errors.mjs';
import { claimInput, text } from './validation.mjs';
import { calculateCredit } from './policy.mjs';
const transitions = { validateMeasurement: { from: 'calculated', to: 'validated', role: 'service_evidence_reviewer', event: 'credit_measurement_validated' }, approveCredit: { from: 'validated', to: 'approved', role: 'contract_credit_authority', event: 'credit_approved' }, issueCredit: { from: 'approved', to: 'issued', role: 'finance_credit_registrar', event: 'credit_issued' } };
const now = () => new Date().toISOString(); const requireRole = (currentActor, requiredRole) => { if (!currentActor?.id || currentActor.role !== requiredRole) throw forbidden(`role ${requiredRole} is required`); }; const requestSeen = (database, requestId) => database.creditClaims.some((claim) => claim.events.some((entry) => entry.requestId === requestId)); const event = (type, currentActor, requestId, at, note, details = {}) => ({ type, actorId: currentActor.id, requestId, at, note, ...details });
export class ContractServiceCreditService {
  constructor(store) { this.store = store; }
  create(input, currentActor, requestId) { requireRole(currentActor, 'service_monitor'); const database = this.store.read(); if (requestSeen(database, requestId)) throw conflict('request identifier was already used'); const claim = claimInput(input); const at = now(); const record = { id: crypto.randomUUID(), ...claim, status: 'submitted', calculation: null, createdAt: at, updatedAt: at, events: [event('credit_claim_submitted', currentActor, requestId, at)] }; database.creditClaims.push(record); this.store.write(database); return record; }
  transition(id, action, input, currentActor, requestId) { const database = this.store.read(); const record = database.creditClaims.find((claim) => claim.id === id); if (!record) throw missing('credit claim was not found'); if (requestSeen(database, requestId)) throw conflict('request identifier was already used'); if (action === 'calculateCredit') return this.calculate(record, input, currentActor, requestId, database); const policy = transitions[action]; if (!policy) throw missing('action was not found'); requireRole(currentActor, policy.role); if (record.status !== policy.from) throw conflict(`credit claim must be ${policy.from}`); const at = now(); record.status = policy.to; record.updatedAt = at; record.events.push(event(policy.event, currentActor, requestId, at, text(input.note, 'note'), action === 'approveCredit' ? { creditAmount: record.calculation.creditAmount } : {})); this.persist(database); return record; }
  calculate(record, input, currentActor, requestId, database) { requireRole(currentActor, 'service_monitor'); if (record.status !== 'submitted') throw conflict('credit claim must be submitted'); const at = now(); record.calculation = calculateCredit(record); record.status = record.calculation.creditAmount > 0 ? 'calculated' : 'no_credit_due'; record.updatedAt = at; record.events.push(event('credit_calculated', currentActor, requestId, at, text(input.note, 'note'), { creditAmount: record.calculation.creditAmount, meetsTarget: record.calculation.meetsTarget })); this.persist(database); return record; }
  persist(database) { this.store.write({ creditClaims: database.creditClaims }); }
  get(id) { const record = this.store.read().creditClaims.find((claim) => claim.id === id); if (!record) throw missing('credit claim was not found'); return record; }
}
