import { inputError } from './errors.mjs';
export const text = (value, name) => { if (typeof value !== 'string' || !value.trim()) throw inputError(`${name} is required`); return value.trim(); };
export const percentage = (value, name, minimum = 0, maximum = 100) => { if (typeof value !== 'number' || !Number.isFinite(value) || value < minimum || value > maximum) throw inputError(`${name} must be a number from ${minimum} through ${maximum}`); return Math.round(value * 100) / 100; };
export const money = (value, name) => { if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) throw inputError(`${name} must be greater than zero`); return Math.round(value * 100) / 100; };
export const wholeNumber = (value, name, minimum = 0) => { if (!Number.isInteger(value) || value < minimum) throw inputError(`${name} must be an integer of at least ${minimum}`); return value; };
export const bands = (value) => {
  if (!Array.isArray(value) || value.length < 1 || value.length > 8) throw inputError('one through eight credit bands are required'); const thresholds = new Set();
  return value.map((band) => { if (!band || typeof band !== 'object') throw inputError('credit band is invalid'); const upperAvailabilityPct = percentage(band.upperAvailabilityPct, 'band availability'); if (thresholds.has(upperAvailabilityPct)) throw inputError('credit band thresholds must be unique'); thresholds.add(upperAvailabilityPct); return { upperAvailabilityPct, creditPct: percentage(band.creditPct, 'credit percentage') }; });
};
export const claimInput = (value) => { if (!value || typeof value !== 'object') throw inputError('credit claim is required'); return { contractId: text(value.contractId, 'contract id'), serviceName: text(value.serviceName, 'service name'), reportingPeriod: text(value.reportingPeriod, 'reporting period'), monthlyFee: money(value.monthlyFee, 'monthly fee'), targetAvailabilityPct: percentage(value.targetAvailabilityPct, 'target availability'), maximumCreditPct: percentage(value.maximumCreditPct, 'maximum credit percentage'), creditBands: bands(value.creditBands), measuredAvailabilityPct: percentage(value.measuredAvailabilityPct, 'measured availability'), incidentMinutes: wholeNumber(value.incidentMinutes, 'incident minutes', 0), evidenceReference: text(value.evidenceReference, 'evidence reference') }; };
export const actor = (headers) => ({ id: headers['x-actor-id'], role: headers['x-actor-role'] });
